
all:
	@g++ -oBurbuja.bin Burbuja.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo iterativo con ./Burbuja.bin salida.txt 12345 1000 2000 3000
	@g++ -oMergeSort.bin mergesort.cpp -std=c++11
	@echo Pruebe a ejecutar el algoritmo recursivo con ./MergeSort.bin salida.txt 12345 1000 2000 3000
